### ISSUE TITLE
[ERR] Preference/Provider/Recount button: App crashes after the test is performed

### ISSUE THREAD

**Issue by beralt85** [imapp-pl/golem-docs#11]
As said above. Log indicated `golemapp: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.`

[golem  Mon Aug 22 21:51:31 CEST 2016.log.tar.gz](https://github.com/imapp-pl/golem-docs/files/431043/golem.Mon.Aug.22.21.51.31.CEST.2016.log.tar.gz)

**Comment by mfranciszkiewicz** [comment]
We have released an update, can you confirm that this issue has been resolved? Golem should update itself on the next run.

**Comment by beralt85** [comment]
Yep. The issue is resolved. Thanks!
