### ISSUE TITLE
[ERR] Subtasks execute as root

### ISSUE THREAD

**Issue by pcbaer** [imapp-pl/golem-docs#8]
Whem my Golem runs a subtask, blender is running as root. I think this is because docker is running as root. This is very unpleasant, but I suppose it's because we're in Alpha test stage, right? I would have no confidence in Golem if it runs its subtasks as root.

**Comment by magdasta** [comment]
You can create a docker group and add your user to it to avoid running docker as root (here is the instruction: https://docs.docker.com/engine/installation/linux/ubuntulinux/)

**Comment by pcbaer** [comment]
I did that. But it seems this just allows a user to run the docker command without sudo. See here:
https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
It states that docker "currently requires root privileges".

**Comment by mfranciszkiewicz** [comment]
A Docker container is a sandbox, so all actions performed in the container are isolated from the host. This also applies to programs running with root privileges. However, it is possible to run subtasks as a non-root user and it's on our to-do list.

**Comment by pcbaer** [comment]
That's right, they are isolated. But... ;-)
Btw, is it the plan to use docker after Alpha/Beta phase? I guess there are good reasons to do so (have the computing software version the same on every node etc., isolation).

**Comment by mfranciszkiewicz** [comment]
Resolved
